### ISSUE TITLE
Feature request: shortcut for launching default terminal/editor

### ISSUE THREAD

**Issue by AreamanM** [lars-berger/GlazeWM#104]
Hi, first of all, I'd like to say that this is the best WM I've used on Windows so far; thank you for the excellent work!

Something convenient I've seen in typical linux WMs is the ability to launch a terminal/editor with a shortcut, and I was wondering if that is something you would consider for Glaze as well? There are already many shortcuts that depend on the alt key, so it's understandable if you'd prefer to not add yet another one or two, but something like alt+t to launch your preferred terminal program would be neat for example.

I can definitely have a go at making a PR if you'd like to consider this feature.

**Comment by es183923** [comment]
this can easily be done with autohotkey. not sure if this is in scope for GlazeWM though.

**Comment by AreamanM** [comment]
While Autohotkey is definitely a solution, the reason I was wondering if it could be implemented into Glaze is because

- it would make Glaze a bit more feature consistent with typical WMs 
- it removes the need for an extra dependency(AHK) for typical WM functionality

Although if it is not in scope for Glaze, I completely understand.

**Comment by ParasiteDelta** [comment]
I think this would be a nice feature, since I think you can launch external processes natively from C# as long as you've provided a correct path. The real trick, however, is the number of differences between Windows and Linux. In Linux, your terminal and sudo can control and do basically everything. In Windows, some things require Powershell, others can only be done from Command Line, or just Windows Terminal if you really want to do it that way. You have the Run command, Win+X, and even alternative start menus to fill the role of quick execution. However, these things do highlight the issue: a need for a unified system for shortcuts without patching together programs, hotkey programs, and scripts.

So, how could it be done? Well, you could potentially integrate it into the existing command structure as a new command, where the user just provides a path to a binary, so maybe


```
 - command: "launch program"
    path_to_program: "G:\SomeDir\lolz.exe"
```

would be the resulting config value? This could also lend itself into more dynamic window control based on type, as hinted at by #105, but that's just my guess.

Good luck to you wizards who use C#, for I will never understand how you do it.

**Comment by lars-berger** [comment]
I agree it'd be a nice feature, especially if you want keybindings that only fire when GlazeWM is active. 

IMO the best way to implement this would be to use the [`start`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start) command built into `cmd.exe`. It's what's used under the hood when you use Windows Run (`LWin+R`). This lets you launch an app through its process name or a path to the `.exe`, for example:

```
start firefox
start code ./file.txt
start "" "C:\Program Files\Mozilla Firefox\firefox.exe"
```

It also lets you run shell scripts:

```
start cmd /c C:\Users\lars\script.bat
start powershell C:\Users\lars\script.ps1
start wsl /mnt/c/Users/lars/script.sh
```

So what could be done is add a command for calling `start` and just forward any args/flags. It seems pretty doable to start a `cmd.exe` process and run the appropriate `start` command from C#.

```yaml
keybindings:
  # Launch Windows terminal.
  - command: "start wt"
    bindings: "Alt+Enter"
    
  # Run a batch script.
  - command: "start cmd /c C:\Users\lars\script.bat"
    bindings: "Alt+B"
```

@AreamanM  LMK if you want to take a stab at it. If you've got any Q's, message me on discord `@lberger#4570`

**Comment by AreamanM** [comment]
I'm definitely up for giving this is a shot. So just to be clear the idea is that if the first word of the `command` key is "start", then the keybind launches the process specified in the `command` key using the `start` command?

**Comment by lars-berger** [comment]
@AreamanM Yeah exactly. You can take a look at `CommandParsingService` to see how the other commands are parsed. Also, the logic for commands is usually put under a dir for their respective entity (eg. workspace-related commands go under `GlazeWM.Domain.Workspaces`). Since there isn't really a good spot to put this command, `GlazeWM.Domain.Common` might be the best place to slap the new command & command handler.

**Comment by lars-berger** [comment]
This has been added in the [latest 1.7 release](https://github.com/lars-berger/GlazeWM/releases) :tada:
