### ISSUE TITLE
Handle windows that are forcefully shown from a hidden workspace

### ISSUE THREAD

**Issue by NathanViau** [lars-berger/GlazeWM#173]
All in title, 
situation : discord on a workspace (link in a channel), and a browser open in an OTHER workspace

Thx for reading

**Comment by lars-berger** [comment]
The OS forcefully shows chrome when an app opens chrome and it's in a hidden workspace. This confuses the WM since it thinks chrome is in workspace X, it assumes workspace X is currently focused (and displays that as the focused workspace in the bar).

Like say you have 1 monitor with workspace 1, which has Discord open, and workspace 2 which has Chrome open. If you open a Discord link, the OS will show Chrome and the WM thinks workspace 2 now has focus (but workspace 1 is actually still displayed at the same time). 

There are 2 solutions, and I'm not sure which one is best:
* When a hidden window is shown, hide the current workspace (eg. workspace 1 with Discord) and switch focus to the workspace that has the shown window.
* Move the shown window to the current workspace. So in the example, this would kill workspace 2, and move Chrome to workspace 1 together with Discord.

**Comment by gtsherman** [comment]
For what it's worth, I vote for option 1 (switch workspace focus). For me, clicking a link indicates that I want to switch my focus, not that I want to reorganize my workspace.

**Comment by lars-berger** [comment]
@gtsherman Yeah true, that's a good point. 

If I remember correctly, i3 stays on the current workspace, but flashes the other workspace as "urgent" in the bar. I don't think it'd be a good experience on Windows though. Since the OS shows the window no matter what, the WM would have to try to immediately hide it again, and then flash the other workspace as urgent...
