### ISSUE TITLE
Inner gaps not respecting 0

### ISSUE THREAD

**Issue by BuriedStPatrick** [lars-berger/GlazeWM#33]
First off: Great initiative and good job! Loving the push for window managers in Windows and YAML is a great choice for configs.

Now to the issue I'm experiencing.

There seems to be an issue with the inner gaps where it doesn't allow you to go below a certain threshold.

My `~/.glaze-wm/config.yaml` (everything else is left at default):

```yaml
gaps:
  inner_gap: 0
  outer_gap: 0
...
```

## Expected behavior

Expected no gaps between my windows.

## Actual behavior

Found gaps on both vertical as well as horizontal layouts. See screenshot:

![image](https://user-images.githubusercontent.com/3541466/163607739-6c9ae9d2-81cf-4b21-ae90-da19f78fd66e.png)

| Spec | Info |
|---|---|
| OS | Windows 11 |
| Built from | https://github.com/lars-berger/GlazeWM/commit/c4ee4991782536b537cb018567a67386f46a292c  |
| Built with | .NET SDK 6.0.101 |
| Screen resolution | 3440x1440 |

NOTE: I also tried the latest binary (v1.2.0) but it has the same problem.

**Comment by LGUG2Z** [comment]
This looks like it might be related to the invisible borders that are drawn around every window on Windows 10/11.

The invisible borders are a little bit tricky because they aren't always exactly the same between different devices or updates in my experience. My approach to this was to make the invisible border dimensions configurable by the user, and then [use those dimensions to adjust the size of the window immediately before setting its position](https://github.com/LGUG2Z/komorebi/blob/master/komorebi/src/window.rs#L129).

This approach unfortunately introduced a second issue, which is that more and more primarily Electron apps are deliberately drawing over the invisible borders, so if you adjust the size of the window to remove the borders, you actually end up with an app window that is larger in size than it is supposed to be. I handled this by allowing users to identify applications that overflow their borders and [handling that case separately](https://github.com/LGUG2Z/komorebi/blob/master/komorebi/src/window.rs#L121).

Hope this helps!

**Comment by lars-berger** [comment]
@LGUG2Z I seriously appreciate the help, thank you! It seemed at first like this was only an issue for certain apps, since I was seeing that VSCode was filling the whole screen. But like you said, Electron apps extend past the invisible borders compared to most other windows.

For handling the apps that have non-standard invisible borders, will look into making it possible for users to add a window rule to adjust for these dimensions. Maybe something like this: 

```yaml
window_rules:
  - commands: ["crop height -7px", "crop width -7px"]
  match_process_name: "chrome"
```

Might take a few days to get in a fix for this, but will try to address it ASAP.

**Comment by lars-berger** [comment]
This has been addressed now in the [latest release](https://github.com/lars-berger/GlazeWM/releases/tag/v1.4.0) 👍

A new `"resize borders"` command  was added in case there are still windows smaller/larger than others. Example usage:

```yaml
window_rules:
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"
```
