### ISSUE TITLE
Workspaces are not shown across all Monitors on Topbar

### ISSUE THREAD

**Issue by Entharia** [lars-berger/GlazeWM#376]
There are workspaces defined in the config,
those workspaces are not visible in the topbar.
Only after assigning a window to a workspace does the workspace appear on the topbar.

Also the workspace is only visible on one Display not both.

**Comment by notblam** [comment]
Could you provide what your doing in your config.yaml and some screenshots?  It's unclear what your reporting.

**Comment by Entharia** [comment]
Im not doing anything special in my config.

I want my empty workspaces displayed on the top bar, just like the example in workspacer:
![grafik](https://github.com/lars-berger/GlazeWM/assets/59421695/319b9a4b-a6dd-407d-9666-b500145c8b41)


This bar should be consistent across all monitors, with only the active workspace differing per monitor.

Additionally, if workspace 1 is on monitor 1 and workspace 2 is on monitor 2, clicking workspace 1 on monitor 2 should swap the active workspaces between the two monitors.

If this is not possible by using the config and needs some code changes i will be happy to do it myself and open a PR on this.

**Comment by lars-berger** [comment]
@Entharia This is expected behavior - workspacer's design is very different from GlazeWM. Our window manager is more like i3wm, where workspaces are tied to a specific monitor (that's why not all workspaces are shown in the bar). This has the advantage of being able to swap the windows shown on each monitor.

If you'd like to show all workspaces that are in your config, you can add the `keep_alive` flag, which will stop the workspace from deactivating if it's empty.

```yaml
workspaces:
  - name: "1"
    keep_alive: true
  ```
