### ISSUE TITLE
Where to find a list of available tasks?

### ISSUE THREAD

**Issue by arise-project** [lars-berger/GlazeWM#53]
I can help to do. I have some prod skills in wpf and project reunion for me, but can not change any code without mantainers ideas.

thnks

**Comment by scubamount** [comment]
Although I have tried using procmon and task manager, I can't seem to isolate pop up window boxes for explorer and the like... Is there also a way to ignore-next-opened-window?

**Comment by lars-berger** [comment]
@arise-project That's cool that you want to help out! Will start adding tasks in the "Projects" tab pretty soon, so it's easier for contributors to find tasks.

@scubamount If you're having trouble getting the process name of a window to ignore, you could also try matching with the window title (via `match_title`). Note that there was a bug with the `ignore` command, which is fixed in the [latest release](https://github.com/lars-berger/GlazeWM/releases).

**Comment by arise-project** [comment]
ok. Tag me or better send a mail to pirogov.e@gmail.com
here in UA a better get to work when to see nightmare

**Comment by lars-berger** [comment]
Moved over tasks to a public [Github project board here](https://github.com/lars-berger/GlazeWM/projects) :+1:
