### ISSUE TITLE
Workspace one on Monitor 2

### ISSUE THREAD

**Issue by bigfoote** [lars-berger/GlazeWM#59]
First, thank for this great project!

I'm running in with two monitors, and I know you already have an issue open for moving entire workspaces to specific monitors, but I was wondering if there's some config problem since my left monitor has workspace 2, 3, 4, and 5, and my right monitor has workspace 1, 6, 7, 8, and 9. I noticed Windows thought of my left monitor as monitor 2 and the right as monitor 1, but swapping the cables to fix that seemed to have no effect.

**Comment by bigfoote** [comment]
Great question. In i3 I configure workspaces 1-5 on my left monitor and 6-10 on the right, per their instructions at https://i3wm.org/docs/userguide.html#workspace_screen. I'm not sure what happens without any configuration, but the result I described above doesn't seem like a good default.

This also means I don't understand how Windows chooses the order of Screen.AllScreens. Why wouldn't display #1 come first?

**Comment by KiLLeRRaT** [comment]
It would be great to have a feature to always have spaces say, 123 on screen 1, 456 on screen 2, and 789 on screen 3.

An alternative could be to count all 3 my screens as a single space, so when swapping to space two, all 3 my screens' apps change. Almost how Windows treats the separate desktops.  This will work well because you can already navigate from screen 1 to screen 2 just using say, `alt + l` repeatedly.

**Comment by lyze237** [comment]
That has just been merged into master! #41

**Comment by lars-berger** [comment]
This has been added in the [latest 1.7 release](https://github.com/lars-berger/GlazeWM/releases) :tada:
