### ISSUE TITLE
Weird resizing rules with hidden task bar

### ISSUE THREAD

**Issue by Cyklan** [lars-berger/GlazeWM#63]
I use a program called [Taskbar Hider](http://www.itsamples.com/taskbar-hider.html) to, well, hide my task bar.
The windows only get adjusted to the new height on one monitor, with the other one being stuck on the same height it would have with the task bar shown, creating a big gap at the bottom of the screen

[Works well on Screen 1](https://i.imgur.com/yKN1phN.png)

[Does not work well on Screen 2](https://i.imgur.com/O5IVkal.png)

[Same happening with multiple windows](https://i.imgur.com/4Zn3MuC.png)

**Comment by lars-berger** [comment]
Is there still a gap at the bottom of the screen if the taskbar hider is launched prior to the WM?

**Comment by Cyklan** [comment]
Yes, but I did some more investigating. When running taskbar hider, only the taskbar on my main monitor would get hidden, the second one requires a second toggle.

I found a workaround though, by disabling the windows option to have the task bar on multiple monitors. [Now it works as intended.](https://i.imgur.com/mVzBHJU.png)

**Comment by lars-berger** [comment]
Ah awesome, glad you found a workaround 👍 

Took a quick peek at the source code for Taskbar Hider and I'm inclined to believe the issue is on their end. When tiling, the WM gets the working area from the Windows API, but Taskbar Hider seems to only adjust the working area based on the main taskbar window via [`SystemParametersInfo(SPI_SETWORKAREA, ...)`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-systemparametersinfow).
