### ISSUE TITLE
Cobian Backup - auto selecting "Run All Tasks Now"

### ISSUE THREAD

**Issue by nascentt** [lars-berger/GlazeWM#71]
Similar to the notepadplus issue and keepass issue, when opening the main window of Cobain Backup, it seems to select 2Run All Tasks Now". 

 Not sure what info you use to exclude these, I can provide more info in the future.

Main window:
Title: Cobian Backup 11 Gravity
class: TformMain

**Comment by lars-berger** [comment]
Actually added a fix in v1.4.0 hoping to resolve issues like these. This one seems quite different from the previous cases though. With the previous issues, the apps were spawning child windows that the WM should have ignored.

Cobian Backup is for some reason opening a dialog when focus is set to the main window programmatically. You can see what I mean if you focus Cobian Backup and then minimize a sibling window. The WM will set focus back to Cobian Backup, which triggers it to open a dialog. There aren't any rogue menu windows or anything that WM is trying to manage. Honestly have no idea why this would happen since the exact same process name & class name gains focus when you focus it naturally via clicking.

Unfortunately, I don't think anything can be done to handle it better and your best bet is simply ignoring the window.
