### ISSUE TITLE
Qt windows not hooking? (OBS as a notable example)

### ISSUE THREAD

**Issue by ParasiteDelta** [lars-berger/GlazeWM#91]
So, I use a few tools that use Qt for Windows, including OBS Studio. Regardless of what I try, it's like it either fails to manage entirely (Czkawka/Szyszka) or it attempts to manage with a large gap in the current layout but with no actual management taking place (OBS Studio). Is Qt support simply not a thing for the WM currently?

OBS Studio:
![image](https://user-images.githubusercontent.com/19669733/180618644-60a2e343-5073-4b9c-940f-3341178d1c7c.png)

**Comment by lars-berger** [comment]
OBS is actually behaving normally on my machine. Could you double check that it's not being run as administrator? [It might be default set in the "Compatibility" settings](https://user-images.githubusercontent.com/34844898/180619495-369365f0-85a7-4eb2-8cb0-a2ec3724cf6e.png).

Czkawka also seems to be behaving normally, but it initializes as floating instead of tiling (`Alt+Shift+Space` is the default keybinding for toggling between floating/tiling). It also has huge borders that need to be corrected for to tile properly.

You can try adding this window rule and see if it works how you like:

```yaml
window_rules:
  - commands: ["resize borders 22px 22px 22px 22px", "toggle floating"]
    match_process_name: "czkawka_gui"
```

**Comment by ParasiteDelta** [comment]
Okay, sometimes I really hate Windows 10. Indeed, OBS Studio's been running as Admin despite me not <at least remembering> setting the flag, but I have heard of issues where OBS has trouble capturing games on certain rigs when not run as Admin, so maybe that's why it was set? Eh, I'll test and deal with that on my end, but yes, it looks like another example of #32. As far as Czkawka, thank you for the specification, I wasn't sure if it was me or the program or whatever. This'll help me iron out Steam's weirdness as well.
